# Generated by Django 2.0.4 on 2019-04-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='github',
            name='about',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
